# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)


Country.create([{ :name => 'Afghanistan', :code => 'AF' },
                { :name => 'Albania', :code => 'AL' },
                { :name => 'Algeria', :code => 'DZ' },
                { :name => 'American Samoa', :code => 'AS' },
                { :name => 'Andorra', :code => 'AD' },
                { :name => 'Angola', :code => 'AO' },
                { :name => 'Anguilla', :code => 'AI' },
                { :name => 'Antarctica', :code => 'AQ' },
                { :name => 'Antigua and Barbuda', :code => 'AG' },
                { :name => 'Argentina', :code => 'AR' },
                { :name => 'Armenia', :code => 'AM' },
                { :name => 'Aruba', :code => 'AW' },
                { :name => 'Australia', :code => 'AU' },
                { :name => 'Austria', :code => 'AT' },
                { :name => 'Azerbaijan', :code => 'AZ' },
                { :name => 'Bahamas', :code => 'BS' },
                { :name => 'Bahrain', :code => 'BH' },
                { :name => 'Bangladesh', :code => 'BD' },
                { :name => 'Barbados', :code => 'BB' },
                { :name => 'Belarus', :code => 'BY' },
                { :name => 'Belgium', :code => 'BE' },
                { :name => 'Belize', :code => 'BZ' },
                { :name => 'Benin', :code => 'BJ' },
                { :name => 'Bermuda', :code => 'BM' },
                { :name => 'Bhutan', :code => 'BT' },
                { :name => 'Bolivia', :code => 'BO' },
                { :name => 'Bosnia and Herzegovina', :code => 'BA' },
                { :name => 'Botswana', :code => 'BW' },
                { :name => 'Bouvet Island', :code => 'BV' },
                { :name => 'Brazil', :code => 'BR' },
                { :name => 'British Indian Ocean Territory', :code => 'IO' },
                { :name => 'Brunei Darussalam', :code => 'BN' },
                { :name => 'Bulgaria', :code => 'BG' },
                { :name => 'Burkina Faso', :code => 'BF' },
                { :name => 'Burundi', :code => 'BI' },
                { :name => 'Cambodia', :code => 'KH' },
                { :name => 'Cameroon', :code => 'CM' },
                { :name => 'Canada', :code => 'CA' },
                { :name => 'Cape Verde', :code => 'CV' },
                { :name => 'Cayman Islands', :code => 'KY' },
                { :name => 'Central African Republic', :code => 'CF' },
                { :name => 'Chad', :code => 'TD' },
                { :name => 'Chile', :code => 'CL' },
                { :name => 'China', :code => 'CN' },
                { :name => 'Christmas Island', :code => 'CX' },
                { :name => 'Cocos (Keeling) Islands', :code => 'CC' },
                { :name => 'Colombia', :code => 'CO' },
                { :name => 'Comoros', :code => 'KM' },
                { :name => 'Congo', :code => 'CG' },
                { :name => 'Congo, the Democratic Republic of the', :code => 'CD' },
                { :name => 'Cook Islands', :code => 'CK' },
                { :name => 'Costa Rica', :code => 'CR' },
                { :name => 'Cote D\'Ivoire', :code => 'CI' },
                { :name => 'Croatia', :code => 'HR' },
                { :name => 'Cuba', :code => 'CU' },
                { :name => 'Cyprus', :code => 'CY' },
                { :name => 'Czech Republic', :code => 'CZ' },
                { :name => 'Denmark', :code => 'DK' },
                { :name => 'Djibouti', :code => 'DJ' },
                { :name => 'Dominica', :code => 'DM' },
                { :name => 'Dominican Republic', :code => 'DO' },
                { :name => 'Ecuador', :code => 'EC' },
                { :name => 'Egypt', :code => 'EG' },
                { :name => 'El Salvador', :code => 'SV' },
                { :name => 'Equatorial Guinea', :code => 'GQ' },
                { :name => 'Eritrea', :code => 'ER' },
                { :name => 'Estonia', :code => 'EE' },
                { :name => 'Ethiopia', :code => 'ET' },
                { :name => 'Falkland Islands (Malvinas)', :code => 'FK' },
                { :name => 'Faroe Islands', :code => 'FO' },
                { :name => 'Fiji', :code => 'FJ' },
                { :name => 'Finland', :code => 'FI' },
                { :name => 'France', :code => 'FR' },
                { :name => 'French Guiana', :code => 'GF' },
                { :name => 'French Polynesia', :code => 'PF' },
                { :name => 'French Southern Territories', :code => 'TF' },
                { :name => 'Gabon', :code => 'GA' },
                { :name => 'Gambia', :code => 'GM' },
                { :name => 'Georgia', :code => 'GE' },
                { :name => 'Germany', :code => 'DE' },
                { :name => 'Ghana', :code => 'GH' },
                { :name => 'Gibraltar', :code => 'GI' },
                { :name => 'Greece', :code => 'GR' },
                { :name => 'Greenland', :code => 'GL' },
                { :name => 'Grenada', :code => 'GD' },
                { :name => 'Guadeloupe', :code => 'GP' },
                { :name => 'Guam', :code => 'GU' },
                { :name => 'Guatemala', :code => 'GT' },
                { :name => 'Guinea', :code => 'GN' },
                { :name => 'Guinea-Bissau', :code => 'GW' },
                { :name => 'Guyana', :code => 'GY' },
                { :name => 'Haiti', :code => 'HT' },
                { :name => 'Heard Island and Mcdonald Islands', :code => 'HM' },
                { :name => 'Holy See (Vatican City State)', :code => 'VA' },
                { :name => 'Honduras', :code => 'HN' },
                { :name => 'Hong Kong', :code => 'HK' },
                { :name => 'Hungary', :code => 'HU' },
                { :name => 'Iceland', :code => 'IS' },
                { :name => 'India', :code => 'IN' },
                { :name => 'Indonesia', :code => 'ID' },
                { :name => 'Iran, Islamic Republic of', :code => 'IR' },
                { :name => 'Iraq', :code => 'IQ' },
                { :name => 'Ireland', :code => 'IE' },
                { :name => 'Israel', :code => 'IL' },
                { :name => 'Italy', :code => 'IT' },
                { :name => 'Jamaica', :code => 'JM' },
                { :name => 'Japan', :code => 'JP' },
                { :name => 'Jordan', :code => 'JO' },
                { :name => 'Kazakhstan', :code => 'KZ' },
                { :name => 'Kenya', :code => 'KE' },
                { :name => 'Kiribati', :code => 'KI' },
                { :name => 'Korea, Democratic People\'s Republic of', :code => 'KP' },
                { :name => 'Korea, Republic of', :code => 'KR' },
                { :name => 'Kuwait', :code => 'KW' },
                { :name => 'Kyrgyzstan', :code => 'KG' },
                { :name => 'Lao People\'s Democratic Republic', :code => 'LA' },
                { :name => 'Latvia', :code => 'LV' },
                { :name => 'Lebanon', :code => 'LB' },
                { :name => 'Lesotho', :code => 'LS' },
                { :name => 'Liberia', :code => 'LR' },
                { :name => 'Libyan Arab Jamahiriya', :code => 'LY' },
                { :name => 'Liechtenstein', :code => 'LI' },
                { :name => 'Lithuania', :code => 'LT' },
                { :name => 'Luxembourg', :code => 'LU' },
                { :name => 'Macao', :code => 'MO' },
                { :name => 'Macedonia, the Former Yugoslav Republic of', :code => 'MK' },
                { :name => 'Madagascar', :code => 'MG' },
                { :name => 'Malawi', :code => 'MW' },
                { :name => 'Malaysia', :code => 'MY' },
                { :name => 'Maldives', :code => 'MV' },
                { :name => 'Mali', :code => 'ML' },
                { :name => 'Malta', :code => 'MT' },
                { :name => 'Marshall Islands', :code => 'MH' },
                { :name => 'Martinique', :code => 'MQ' },
                { :name => 'Mauritania', :code => 'MR' },
                { :name => 'Mauritius', :code => 'MU' },
                { :name => 'Mayotte', :code => 'YT' },
                { :name => 'Mexico', :code => 'MX' },
                { :name => 'Micronesia, Federated States of', :code => 'FM' },
                { :name => 'Moldova, Republic of', :code => 'MD' },
                { :name => 'Monaco', :code => 'MC' },
                { :name => 'Mongolia', :code => 'MN' },
                { :name => 'Montserrat', :code => 'MS' },
                { :name => 'Morocco', :code => 'MA' },
                { :name => 'Mozambique', :code => 'MZ' },
                { :name => 'Myanmar', :code => 'MM' },
                { :name => 'Namibia', :code => 'NA' },
                { :name => 'Nauru', :code => 'NR' },
                { :name => 'Nepal', :code => 'NP' },
                { :name => 'Netherlands', :code => 'NL' },
                { :name => 'Netherlands Antilles', :code => 'AN' },
                { :name => 'New Caledonia', :code => 'NC' },
                { :name => 'New Zealand', :code => 'NZ' },
                { :name => 'Nicaragua', :code => 'NI' },
                { :name => 'Niger', :code => 'NE' },
                { :name => 'Nigeria', :code => 'NG' },
                { :name => 'Niue', :code => 'NU' },
                { :name => 'Norfolk Island', :code => 'NF' },
                { :name => 'Northern Mariana Islands', :code => 'MP' },
                { :name => 'Norway', :code => 'NO' },
                { :name => 'Oman', :code => 'OM' },
                { :name => 'Pakistan', :code => 'PK' },
                { :name => 'Palau', :code => 'PW' },
                { :name => 'Palestinian Territory, Occupied', :code => 'PS' },
                { :name => 'Panama', :code => 'PA' },
                { :name => 'Papua New Guinea', :code => 'PG' },
                { :name => 'Paraguay', :code => 'PY' },
                { :name => 'Peru', :code => 'PE' },
                { :name => 'Philippines', :code => 'PH' },
                { :name => 'Pitcairn', :code => 'PN' },
                { :name => 'Poland', :code => 'PL' },
                { :name => 'Portugal', :code => 'PT' },
                { :name => 'Puerto Rico', :code => 'PR' },
                { :name => 'Qatar', :code => 'QA' },
                { :name => 'Reunion', :code => 'RE' },
                { :name => 'Romania', :code => 'RO' },
                { :name => 'Russian Federation', :code => 'RU' },
                { :name => 'Rwanda', :code => 'RW' },
                { :name => 'Saint Helena', :code => 'SH' },
                { :name => 'Saint Kitts and Nevis', :code => 'KN' },
                { :name => 'Saint Lucia', :code => 'LC' },
                { :name => 'Saint Pierre and Miquelon', :code => 'PM' },
                { :name => 'Saint Vincent and the Grenadines', :code => 'VC' },
                { :name => 'Samoa', :code => 'WS' },
                { :name => 'San Marino', :code => 'SM' },
                { :name => 'Sao Tome and Principe', :code => 'ST' },
                { :name => 'Saudi Arabia', :code => 'SA' },
                { :name => 'Senegal', :code => 'SN' },
                { :name => 'Serbia and Montenegro', :code => 'CS' },
                { :name => 'Seychelles', :code => 'SC' },
                { :name => 'Sierra Leone', :code => 'SL' },
                { :name => 'Singapore', :code => 'SG' },
                { :name => 'Slovakia', :code => 'SK' },
                { :name => 'Slovenia', :code => 'SI' },
                { :name => 'Solomon Islands', :code => 'SB' },
                { :name => 'Somalia', :code => 'SO' },
                { :name => 'South Africa', :code => 'ZA' },
                { :name => 'South Georgia and the South Sandwich Islands', :code => 'GS' },
                { :name => 'Spain', :code => 'ES' },
                { :name => 'Sri Lanka', :code => 'LK' },
                { :name => 'Sudan', :code => 'SD' },
                { :name => 'Suriname', :code => 'SR' },
                { :name => 'Svalbard and Jan Mayen', :code => 'SJ' },
                { :name => 'Swaziland', :code => 'SZ' },
                { :name => 'Sweden', :code => 'SE' },
                { :name => 'Switzerland', :code => 'CH' },
                { :name => 'Syrian Arab Republic', :code => 'SY' },
                { :name => 'Taiwan, Province of China', :code => 'TW' },
                { :name => 'Tajikistan', :code => 'TJ' },
                { :name => 'Tanzania, United Republic of', :code => 'TZ' },
                { :name => 'Thailand', :code => 'TH' },
                { :name => 'Timor-Leste', :code => 'TL' },
                { :name => 'Togo', :code => 'TG' },
                { :name => 'Tokelau', :code => 'TK' },
                { :name => 'Tonga', :code => 'TO' },
                { :name => 'Trinidad and Tobago', :code => 'TT' },
                { :name => 'Tunisia', :code => 'TN' },
                { :name => 'Turkey', :code => 'TR' },
                { :name => 'Turkmenistan', :code => 'TM' },
                { :name => 'Turks and Caicos Islands', :code => 'TC' },
                { :name => 'Tuvalu', :code => 'TV' },
                { :name => 'Uganda', :code => 'UG' },
                { :name => 'Ukraine', :code => 'UA' },
                { :name => 'United Arab Emirates', :code => 'AE' },
                { :name => 'United Kingdom', :code => 'GB' },
                { :name => 'United States', :code => 'US' },
                { :name => 'United States Minor Outlying Islands', :code => 'UM' },
                { :name => 'Uruguay', :code => 'UY' },
                { :name => 'Uzbekistan', :code => 'UZ' },
                { :name => 'Vanuatu', :code => 'VU' },
                { :name => 'Venezuela', :code => 'VE' },
                { :name => 'Viet Nam', :code => 'VN' },
                { :name => 'Virgin Islands, British', :code => 'VG' },
                { :name => 'Virgin Islands, U.S.', :code => 'VI' },
                { :name => 'Wallis and Futuna', :code => 'WF' },
                { :name => 'Western Sahara', :code => 'EH' },
                { :name => 'Yemen', :code => 'YE' },
                { :name => 'Zambia', :code => 'ZM' },
                { :name => 'Zimbabwe', :code => 'ZW' }])


Language.create([
                 { :name => 'Abkhazian', :code => 'AB' },
                 { :name => 'Afar', :code => 'AA' },
                 { :name => 'Afrikaans', :code => 'AF' },
                 { :name => 'Albanian', :code => 'SQ' },
                 { :name => 'Amharic', :code => 'AM' },
                 { :name => 'Arabic', :code => 'AR' },
                 { :name => 'Armenian', :code => 'HY' },
                 { :name => 'Assamese', :code => 'AS' },
                 { :name => 'Aymara', :code => 'AY' },
                 { :name => 'Azerbaijani', :code => 'AZ' },
                 { :name => 'Bashkir', :code => 'BA' },
                 { :name => 'Basque', :code => 'EU' },
                 { :name => 'Bengali', :code => 'BN' },
                 { :name => 'Bhutani', :code => 'DZ' },
                 { :name => 'Bihari', :code => 'BH' },
                 { :name => 'Bislama', :code => 'BI' },
                 { :name => 'Breton', :code => 'BR' },
                 { :name => 'Bulgarian', :code => 'BG' },
                 { :name => 'Burmese', :code => 'MY' },
                 { :name => 'Byelorussian', :code => 'BE' },
                 { :name => 'Cambodian', :code => 'KM' },
                 { :name => 'Catalan', :code => 'CA' },
                 { :name => 'Chinese (traditional)', :code => 'ZH_TW' },
                 { :name => 'Chinese (simplified)', :code => 'ZH_CN' },
                 { :name => 'Corsican', :code => 'CO' },
                 { :name => 'Croatian', :code => 'HR' },
                 { :name => 'Czech', :code => 'CS' },
                 { :name => 'Danish', :code => 'DA' },
                 { :name => 'Dutch', :code => 'NL' },
                 { :name => 'English', :code => 'EN' },
                 { :name => 'Esperanto', :code => 'EO' },
                 { :name => 'Estonian', :code => 'ET' },
                 { :name => 'Faeroese', :code => 'FO' },
                 { :name => 'Fiji', :code => 'FJ' },
                 { :name => 'Finnish', :code => 'FI' },
                 { :name => 'French', :code => 'FR' },
                 { :name => 'Frisian', :code => 'FY' },
                 { :name => 'Gaelic', :code => 'GD' },
                 { :name => 'Galician', :code => 'GL' },
                 { :name => 'Georgian', :code => 'KA' },
                 { :name => 'German', :code => 'DE' },
                 { :name => 'Greek', :code => 'EL' },
                 { :name => 'Greenlandic', :code => 'KL' },
                 { :name => 'Guarani', :code => 'GN' },
                 { :name => 'Gujarati', :code => 'GU' },
                 { :name => 'Hausa', :code => 'HA' },
                 { :name => 'Hebrew', :code => 'IW' },
                 { :name => 'Hindi', :code => 'HI' },
                 { :name => 'Hungarian', :code => 'HU' },
                 { :name => 'Icelandic', :code => 'IS' },
                 { :name => 'Indonesian', :code => 'IN' },
                 { :name => 'Interlingua', :code => 'IA' },
                 { :name => 'Interlingue', :code => 'IE' },
                 { :name => 'Inupiak', :code => 'IK' },
                 { :name => 'Irish', :code => 'GA' },
                 { :name => 'Italian', :code => 'IT' },
                 { :name => 'Japanese', :code => 'JA' },
                 { :name => 'Javanese', :code => 'JW' },
                 { :name => 'Kannada', :code => 'KN' },
                 { :name => 'Kashmiri', :code => 'KS' },
                 { :name => 'Kazakh', :code => 'KK' },
                 { :name => 'Kinyarwanda', :code => 'RW' },
                 { :name => 'Kirghiz', :code => 'KY' },
                 { :name => 'Kirundi', :code => 'RN' },
                 { :name => 'Korean', :code => 'KO' },
                 { :name => 'Kurdish', :code => 'KU' },
                 { :name => 'Laothian', :code => 'LO' },
                 { :name => 'Latin', :code => 'LA' },
                 { :name => 'Latvian', :code => 'LV' },
                 { :name => 'Lingala', :code => 'LN' },
                 { :name => 'Lithuanian', :code => 'LT' },
                 { :name => 'Macedonian', :code => 'MK' },
                 { :name => 'Malagasy', :code => 'MG' },
                 { :name => 'Malay', :code => 'MS' },
                 { :name => 'Malayalam', :code => 'ML' },
                 { :name => 'Maltese', :code => 'MT' },
                 { :name => 'Maori', :code => 'MI' },
                 { :name => 'Marathi', :code => 'MR' },
                 { :name => 'Moldavian', :code => 'MO' },
                 { :name => 'Mongolian', :code => 'MN' },
                 { :name => 'Nauru', :code => 'NA' },
                 { :name => 'Nepali', :code => 'NE' },
                 { :name => 'Norwegian', :code => 'NO' },
                 { :name => 'Occitan', :code => 'OC' },
                 { :name => 'Oriya', :code => 'OR' },
                 { :name => 'Oromo', :code => 'OM' },
                 { :name => 'Pashto', :code => 'PS' },
                 { :name => 'Persian', :code => 'FA' },
                 { :name => 'Polish', :code => 'PL' },
                 { :name => 'Portuguese', :code => 'PT' },
                 { :name => 'Português (Brasil)', :code => 'PT_BR' },
                 { :name => 'Punjabi', :code => 'PA' },
                 { :name => 'Quechua', :code => 'QU' },
                 { :name => 'Rhaeto-Romance', :code => 'RM' },
                 { :name => 'Romanian', :code => 'RO' },
                 { :name => 'Russian', :code => 'RU' },
                 { :name => 'Samoan', :code => 'SM' },
                 { :name => 'Sangro', :code => 'SG' },
                 { :name => 'Sanskrit', :code => 'SA' },
                 { :name => 'Serbian', :code => 'SR' },
                 { :name => 'Serbo-Croatian', :code => 'SH' },
                 { :name => 'Sesotho', :code => 'ST' },
                 { :name => 'Setswana', :code => 'TN' },
                 { :name => 'Shona', :code => 'SN' },
                 { :name => 'Sindhi', :code => 'SD' },
                 { :name => 'Singhalese', :code => 'SI' },
                 { :name => 'Siswati', :code => 'SS' },
                 { :name => 'Slovak', :code => 'SK' },
                 { :name => 'Slovenian', :code => 'SL' },
                 { :name => 'Somali', :code => 'SO' },
                 { :name => 'Spanish', :code => 'ES' },
                 { :name => 'Sudanese', :code => 'SU' },
                 { :name => 'Swahili', :code => 'SW' },
                 { :name => 'Swedish', :code => 'SV' },
                 { :name => 'Tagalog', :code => 'TL' },
                 { :name => 'Tajik', :code => 'TG' },
                 { :name => 'Tamil', :code => 'TA' },
                 { :name => 'Tatar', :code => 'TT' },
                 { :name => 'Telugu', :code => 'TE' },
                 { :name => 'Thai', :code => 'TH' },
                 { :name => 'Tibetan', :code => 'BO' },
                 { :name => 'Tigrinya', :code => 'TI' },
                 { :name => 'Tonga', :code => 'TO' },
                 { :name => 'Tsonga', :code => 'TS' },
                 { :name => 'Turkish', :code => 'TR' },
                 { :name => 'Turkmen', :code => 'TK' },
                 { :name => 'Twi', :code => 'TW' },
                 { :name => 'Ukrainian', :code => 'UK' },
                 { :name => 'Urdu', :code => 'UR' },
                 { :name => 'Uzbek', :code => 'UZ' },
                 { :name => 'Vietnamese', :code => 'VI' },
                 { :name => 'Volapuk', :code => 'VO' },
                 { :name => 'Welsh', :code => 'CY' },
                 { :name => 'Wolof', :code => 'WO' },
                 { :name => 'Xhosa', :code => 'XH' },
                 { :name => 'Yiddish', :code => 'JI' },
                 { :name => 'Yoruba', :code => 'YO' },
                 { :name => 'Zulu', :code => 'ZU' }])
